name-template: "v$NEXT_MINOR_VERSION 🌈"
tag-template: "v$NEXT_MINOR_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "✨ Enhancement"
      - "⚒ Refactor"
  - title: "🐛 Bug Fixes"
    labels:
      - "🐞 Bug"
exclude-labels:
  - "📄 Documentation"
  - "🌐 DevOps"
  - "💄 UI/UX"
  - "🏛 Structure"
  - "💖 Question"
  - "☂️ Umbrella"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES
