types: # default: feat | fix | docs | style | refactor | perf | test | build | ci | chore | revert
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - cd
  - wip
  - chore
  - revert
  - Develop to Main
  - Revert
  - Merge
