# Author by chanhihi
# Date 2023.08.22

name: Release Drafter

on:
  pull_request:
    branches:
      - main-ci-cd-test
    types:
      - closed

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Tagging
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.CHANHIHI }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.CHANHIHI }}
