# Author by chanhihi
# Date 2023.08.09

name: Swift Build

on:
  push:
    branches:
      - feat/*
      - fix/*
      - refactor/*

  pull_request:
    branches:
      - cluster_develop

jobs:
  build:
    name: Swift 5.3 on macOS 11
    runs-on: macos-11
    env:
      XCODE_VERSION: "12.4.0"
      SWIFT_VERSION: "5.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.0.app/Contents/Developer'

      - name: Set SDK version
        run: echo 'SDKROOT=/Applications/Xcode_12.4.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' >> $GITHUB_ENV

      - name: setup-swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build
        run: |
          mkdir Sources &&
          mv Box42 Sources/Box42 &&
          swift build
