# Author by chanhihi
# Date 2023.08.09

name: Swift Build

on:
  push:
    branches: [ "feat/*", "fix/*", "refactor/*", "cluster_main", "main" ]
  pull_request:
    branches: [ "cluster_develop" ]

jobs:
  build:
    name: Swift 5.3 on macOS 10.15
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: |
          sudo xcode-select -s '/Applications/Xcode_12.3.app/Contents/Developer'
          echo 'SDKROOT=/Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' >> $GITHUB_ENV

      - name: setup-swift
        uses: swift-actions/setup-swift@v1
        with:
            swift-version: 5.3

      - name: Build
        run: |
          mkdir Sources &&
          mv Box42 Sources/Box42 &&
          swift build

# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
