# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
# Author by chanhihi
# Date 2023.08.09

name: Swift Build and Test

on:
  push:
    branches: [ "feat/*", "fix/*" ]
  pull_request:
    branches: [ "cluster_develop", "cluster_main", "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        swift: ['5.3']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: setup-actions/setup-swift@v3
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
