# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test

on:
  push:
    branches: [ "feat/*", "fix/*" ]
  pull_request:
    branches: [ "cluster_develop", "cluster_main", "main" ]


jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS 10.15.7]
        swift: ["5.3.2"]
    
    runs-on: ${{ matrix.swift }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      with:
        swift-version: ${{ matrix.swift }}
        
    - name: Build
      run: swift build
      
    - name: Run tests
      run: swift test
